django_superhero_project/django_superhero_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_superhero_project/superheroes/urls.py
from django.urls import path
from . import views

app_name = 'superheroes'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('new/', views.create, name='create_new_superhero'),
    path('delete/<int:id>/', views.deleteSuperHero, name='delete_superhero'),
    path('edit/<int:id>/', views.EditSuperHero, name='edit_superhero'),

 
]

django_superhero_project/superheroes/models.py
from django.db import models


# Create your models here.

class Superhero(models.Model):
    objects = None
    name = models.CharField(max_length=50)
    genre = models.CharField(max_length=50)
    runtime = models.IntegerField()
    release_date = models.DateField()
    image = models.ImageField(null=True, blank=True,upload_to='images/')

    def __str__(self):
        return self.name

django_superhero_project/superheroes/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm
from .models import  *


class EditSuperHeroForm(ModelForm):
    class Meta:
        model = Superhero
        fields =  '__all__'
        widgets = {
            'release_date': forms.DateInput(attrs={"class":"form-control bg-gray", "type": "date"}),

        }

django_superhero_project/superheroes/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Superhero
from django.urls import reverse
from django.contrib import messages
from .forms import *
# Create your views here.


def index(request):
    all_superheroes = Superhero.objects.all()
    context = {
        'all_superheroes': all_superheroes
    }
    return render(request, 'superheroes/index.html', context)


def create(request):
    form = EditSuperHeroForm()
    if request.method == 'POST':
        form = EditSuperHeroForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, 'SuperHero created')
        else:
            messages.info(request, 'ups, something went wrong')
        return HttpResponseRedirect(reverse('superheroes:index'))
    context= {
        'form':form
    }

    return render(request, 'superheroes/create.html',context)


def detail(request,id):
    if Superhero.objects.filter(id=id).exists():
        hero = get_object_or_404(Superhero,id=id)
        context = {
            'hero':hero
        }
        return render(request, 'superheroes/details.html',context)
    else:
        return redirect('superheroes:index')


def deleteSuperHero(request,id):
    if Superhero.objects.filter(id=id).exists():
        Superhero.objects.filter(id=id).delete()
        messages.info(request, 'SuperHero deleted')
        return redirect('superheroes:index')
    else:
        return redirect('superheroes:index')

def EditSuperHero(request,id):
    form = EditSuperHeroForm()
    context = {
        'form':form
    }
    if request.method == 'POST':
        name = request.POST['name']
        genre = request.POST['genre']
        runtime = request.POST['runtime']
        release_date = request.POST['release_date']
        if Superhero.objects.filter(id=id).exists():
            Superhero.objects.filter(id=id).update(name=name,genre=genre,runtime=runtime,release_date=release_date)
            messages.info(request, 'SuperHero information updated')
            return redirect('superheroes:index')

    return render(request, 'superheroes/edit_superhero.html',context)

django_superhero_project/superheroes/templates/superheroes/create.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="{% url 'superheroes:create_new_superhero' %}" method=""post>
    {% csrf_token %}
    Name:<input type="text" name="name" id="name"><br>
    Alter Ego:<input type="text" name="alter_ego" id="alter_ego"><br>
    Primary Ability:<input type="text" name="primary_ability" id="primary_ability"><br>
    Secondary Ability:<input type="text" name="secondary_ability" id="secondary_ability"><br>
     Catchphrase:<input type="text" name="catchphrase" id="catchphrase"><br>
    <input type="submit" value="Add new!">
</form>
</body>
</html>

django_superhero_project/superheroes/templates/superheroes/details.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>SyperHero</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Superhero <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'superheroes:create_new_superhero'%}">Add new Superhero<span
                            class="sr-only">(current)</span></a>
                </li>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>SuperHero details</h1>
                {{hero.name}}<br>
                {{hero.genre}}<br>
                {{hero.runtime}}<br>
                {{hero.release_date}}<br>
                _______________________________________<br>
                <a type="submit" class="btn btn-danger"
                    href="{% url 'superheroes:delete_superhero' hero.id %}">delete</a>
                <a type="submit" class="btn btn-secondary"
                    href="{% url 'superheroes:edit_superhero' hero.id %}">edit</a>
            </div>
        </div>
    </div>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

django_superhero_project/superheroes/templates/superheroes/edit_superhero.html
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Superhero</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Superhero <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'superheroes:create_new_superhero'%}">Add new Superhero<span
                            class="sr-only">(current)</span></a>
                </li>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row mt-5">
            <form class="contact-form" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" class="btn btn-primary " value="Edit!">
            </form>
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
</body>

</html>

django_superhero_project/superheroes/templates/superheroes/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Superhero Index</title>
</head>
<body>
<h1>This is a templated view!</h1>
<ul>
    {% for superhero in all_superheroes %}
    <li><h2> {{superhero.name}}</h2>
    <a href ="{% url 'superheroes:detail' superhero.id %}">See more info</a></li>
    {% endfor %}
</ul>
</body>
</html>